[pytest]
pythonpath = .
testpaths = tests
norecursedirs = pytest-cache-files-* __pycache__
asyncio_default_fixture_loop_scope = function
filterwarnings =
	ignore:datetime\.datetime\.utcnow\(\) is deprecated:DeprecationWarning:jose\.jwt
