version: '3.8'

services:
  # 1. AUTH SERVİSİ VE VERİTABANI
  auth_mongo:
    image: mongo:7.0
    container_name: auth_mongo
    networks:
      - internal_network
    # Portlara sadece iç ağdan erişilebilir
    #ports:
    # - "27017:27017"
  auth_service:
    build: ./auth_service
    container_name: auth_service
    restart: always
    environment:
      # Kendi izole veritabanına bağlanıyor
      - MONGO_URL=${AUTH_MONGO_URL:-mongodb://auth_mongo:27017/auth_db}
      - SECRET_KEY=${SECRET_KEY:-yazlab-secret-key}
    networks:
      - internal_network
    depends_on:
      - auth_mongo

  # 2. PRODUCT SERVİSİ VE VERİTABANI
  product_mongo:
    image: mongo:7.0
    container_name: product_mongo
    networks:
      - internal_network

  product_service:
    build: ./product_service
    container_name: product_service
    environment:
      - MONGO_URL=${PRODUCT_MONGO_URL:-mongodb://product_mongo:27017/product_db}
    networks:
      - internal_network
    depends_on:
      - product_mongo

  # 3. ORDER SERVİSİ VE VERİTABANI
  order_mongo:
    image: mongo:7.0
    container_name: order_mongo
    networks:
      - internal_network

  order_service:
    build: ./order_service
    container_name: order_service
    environment:
      - MONGO_URL=${ORDER_MONGO_URL:-mongodb://order_mongo:27017/order_db}
    networks:
      - internal_network
    depends_on:
      - order_mongo

  # 4. API GATEWAY - DISPATCHER
  dispatcher_mongo:
    image: mongo:7.0
    container_name: dispatcher_mongo
    networks:
      - internal_network
  dispatcher:
    build: ./dispatcher
    container_name: dispatcher
    ports:
      - "8000:8000" # Sistemin Dış Dünyaya Açılan Tek Kapısı
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL:-http://auth_service:8000}
      - PRODUCT_SERVICE_URL=${PRODUCT_SERVICE_URL:-http://product_service:8000}
      - ORDER_SERVICE_URL=${ORDER_SERVICE_URL:-http://order_service:8000}
      - MONGO_URL=${DISPATCHER_MONGO_URL:-mongodb://dispatcher_mongo:27017/dispatcher_db}
      - SECRET_KEY=${SECRET_KEY:-yazlab-secret-key}
    networks:
      - internal_network
    depends_on:
      - auth_service
      - product_service
      - order_service

networks:
  internal_network:
    driver: bridge